AllCops:
  RunRailsCops: true
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
   - 'bin/*'
   - 'db/seeds.rb'
   - 'db/schema.rb'
   - 'vendor/bundle/**/*'
LineLength:
  Max: 120
Metrics/LineLength:
  Max: 120
Style/RedundantSelf:
  Enabled: false
Style/RedundantReturn:
  Enabled: false