default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5

development:
  <<: *default
  database: casasmap7_development


test:
  <<: *default
  database: casasmap7_test


production:
  <<: *default
  database: casasmap7_production
  username: casasmap7
  password: <%= ENV['CASASMAP7_DATABASE_PASSWORD'] %>
