# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: demo@example.com
  admin_password: demo1234
  domain_name: casasmap.com
  secret_key_base: c8ae9d4499ecd2ad6ab93a5a9609c14bd9e24bb86c167d22bed438c1808d20210c17f0ca3f8799bf600aeed64f17859e539421d1cdc5201cd200a478db3c40ec

test:
  domain_name: example.com 
  secret_key_base: d1aeafd7d54221fee7d606455ba3773af5e0c66bb09c6f3f1e47ef64b475488a13c9b9c5ff855c95c4f32b7cb34153ac2485327e2b3c5c33fd364cb0e4a78620

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
